name: build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop, release-*]

jobs:
  clean: # Most likely not necessary if using github hosted runners in the future since each job runs in its own special environment.
    if: (github.event_name == 'push' || github.event_name == 'pull_request') && !contains( github.base_ref, 'master')  && !contains(github.base_ref, 'release')
    runs-on: self-hosted
    steps:
      - name: Clean environments
        run: |
          rm -rf ./Archives/
          xcodebuild clean -workspace spotcheck-ios.xcworkspace -scheme "spotcheck-ios (Staging)"
          xcodebuild clean -workspace spotcheck-ios.xcworkspace -scheme "spotcheck-ios (Development)"
          xcodebuild clean -workspace spotcheck-ios.xcworkspace -scheme "spotcheck-ios"
          xcodebuild clean -workspace spotcheck-ios.xcworkspace -scheme "spotcheckr-uitests"

  lint:
    needs: clean
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: norio-nomura/action-swiftlint@3.1.0
        env: # Only lint files in PR.
          DIFF_BASE: ${{ github.base_ref }}

  build:
    needs: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pod install

      - name: (Development) Build environment
        run: >
          xcodebuild build
          -scheme "spotcheck-ios (Development)"
          -workspace spotcheck-ios.xcworkspace
          -allowProvisioningUpdates