name: Swift

on:
  push:
    branches: [ master, hi ]
  pull_request:
    branches: [ master, develop]

jobs:
  build:

    runs-on: [self-hosted, macos]

    steps:
    - name: Github Event
      run: echo "Event - ${{ github.event_name }}"
    - name: Branch name
      run: echo "Branch - githubRef ${{ github.ref }} - baseRef ${{ github.head_ref }}"
      
    - name: Pull Request to master NEED TO TEST
      if: github.event_name == 'pull_request' && contains(github.base_ref, 'master')
      run: echo "Pull Request to ${{ github.base_ref }}(Master) from ${{ github.head_ref }}"

    - name: Pull Request to develop branch
      if: github.event_name == 'pull_request' && contains(github.base_ref, 'develop')
      run: echo "Pull Request to ${{ github.base_ref }}(Master) from ${{ github.head_ref }}"


    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: pod install
    - name: Build
      run: xcodebuild build -scheme "spotcheck-ios (Staging)" -workspace spotcheck-ios.xcworkspace -allowProvisioningUpdates
