name: Swift

on:
  push:
    branches: [ master, develop, hi ]
  pull_request:
    branches: [ master, develop, release-*]

jobs:
  build:

    runs-on: [self-hosted, macos]

    steps:
    - name: Github Event
      run: echo "Event - ${{ github.event_name }}"
    - name: Branch name
      run: echo "Branch - githubRef ${{ github.ref }}"

    - name: Pull Request
      if: github.event_name == 'pull_request'
      run: echo "Pull Request to ${{ github.base_ref }} from ${{ github.head_ref }}"

    - name: Clean Development Scheme
      run: xcodebuild clean -workspace spotcheck-ios.xcworkspace -scheme "spotcheck-ios (Development)"

    - name: Clean Staging Scheme
      run: |
       rm -rf ./Archives/
       xcodebuild clean -workspace spotcheck-ios.xcworkspace -scheme "spotcheck-ios (Staging)"

    - name: Clean Prod Scheme
      run: |
       rm -rf ./Archives/
       xcodebuild clean -workspace spotcheck-ios.xcworkspace -scheme "spotcheck-ios"

    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: pod install

    - name: Build for Development environment (all non-prod events)
      if: github.event_name != 'pull_request' ||  !contains( github.base_ref, 'master')  && !contains(github.base_ref, 'release')
      run: >
       xcodebuild build
       -scheme "spotcheck-ios (Development)"
       -workspace spotcheck-ios.xcworkspace
       -allowProvisioningUpdates

    - name: Archive for Staging environment (all non-prod events) TODO WILL Use this For Staging and Production Schemes only
      if: github.event_name == 'pull_request' && contains(github.base_ref, 'master')
      run: >
       xcodebuild archive
       -scheme "spotcheck-ios (Staging)"
       -workspace spotcheck-ios.xcworkspace
       -allowProvisioningUpdates
       -destination "generic/platform=iOS"
       -archivePath ./Archives/spotcheckr-ios.xcarchive

    - name: Create ipa file from Archive(xcarchive)  should only be for Staging or PRs to Master)
      if: github.event_name == 'pull_request' && contains(github.base_ref, 'master')
      run: >
       xcodebuild -exportArchive
       -archivePath ./Archives/spotcheck-ios.xcarchive
       -exportOptionsPlist ./spotcheck-ios/Configs/exportOptions.plist
       -exportPath ./dist/

    - name: Send to Firebase App Testing (TODO should only be for Staging or PRs to Master)
      run: echo TODO Firebase App Distribution

    - name: Send to App Store
      run: echo TODO this
