name: Swift

on:
  push:
    branches: [ master, update-yaml ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [ macos]

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: pod install
    - name: Build
      run: xcodebuild -scheme spotcheck-ios -workspace spotcheck-ios.xcworkspace -allowProvisioningUpdates
